# Generated by Django 5.2.3 on 2025-07-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_service_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aboutinfo',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
