# Generated by Django 5.2.3 on 2025-07-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_aboutinfo_email_remove_aboutinfo_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdetail',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
