# Generated by Django 5.2.3 on 2025-07-10 08:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_organizationdetail_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutinfo',
            name='features',
        ),
        migrations.RemoveField(
            model_name='aboutinfo',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='aboutinfo',
            name='years_experience',
        ),
        migrations.AlterField(
            model_name='aboutinfo',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
