# Generated by Django 5.2.3 on 2025-07-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_aboutinfo_features_remove_aboutinfo_quote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='description',
            field=models.TextField(),
        ),
    ]
