# Generated by Django 5.2.3 on 2025-07-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_aboutinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinfo',
            name='features',
            field=models.JSONField(default=list),
        ),
    ]
