# Generated by Django 5.2.3 on 2025-08-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_photo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
