# Generated by Django 5.2.3 on 2025-08-04 05:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_aboutinfo_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_strategy', ckeditor.fields.RichTextField(blank=True)),
                ('key_achievement', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
