# Generated by Django 5.2.3 on 2025-08-04 09:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_keyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', ckeditor.fields.RichTextField(verbose_name='Mission Description')),
                ('vision', ckeditor.fields.RichTextField(verbose_name='Vision Description')),
                ('goal', ckeditor.fields.RichTextField(verbose_name='Goal Description')),
                ('objective', ckeditor.fields.RichTextField(verbose_name='Organizational Objective Description')),
                ('value', ckeditor.fields.RichTextField(verbose_name='Organizational Value Description')),
                ('geo_area', ckeditor.fields.RichTextField(verbose_name='Geographical Area Description')),
                ('theme_area', ckeditor.fields.RichTextField(verbose_name='Thematic Area Description')),
            ],
        ),
    ]
