# Generated by Django 5.2.3 on 2025-08-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_coverage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coverage',
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-published_at'], 'verbose_name': 'Notice', 'verbose_name_plural': 'Notices'},
        ),
        migrations.AddField(
            model_name='notice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this notice from the website'),
        ),
    ]
