# Generated by Django 5.2.3 on 2025-08-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
