# Generated by Django 5.2.3 on 2025-08-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_project_attachment_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('opening_date', models.DateField()),
                ('closing_date', models.DateField()),
            ],
        ),
    ]
