# Generated by Django 5.2.3 on 2025-08-21 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('resume', models.FileField(upload_to='career_applications/resumes/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='career_applications/cover_letters/')),
                ('message', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.career')),
            ],
        ),
    ]
