# Generated by Django 5.2.3 on 2025-08-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_careerapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerapplication',
            name='cover_letter',
        ),
    ]
